version: '3.8'
services:
  db:
    image: postgres:15
    container_name: betrillionaire_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mevlut2003
      POSTGRES_DB: betrillionaire
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: