version: '3.8'
services:
  db:
    image: postgres:18
    container_name: betrillionaire_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: hasan1
      POSTGRES_DB: bet
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: